Support for property calculations
openforcefield/openff-qcsubmit pull request #288
Opened 2024-07-09 14:19 UTC by jthorton

## Description
This PR adds better support for property driver psi4 calculations which require the keywords to be formatted differently see this [issue](https://github.com/psi4/psi4/issues/3129) for an example which can be run locally. This also allows for response properties to be calculated such as the dipole polarizabilities, which is included as a new property type. 

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] add tests for the `dipole_polarizabilities` property
  - [x] fix old submission tests

## Questions
- [ ] Question1

## Status
- [x] Ready to go

2024-07-11 18:01 UTC, j-wags requested changes
Good stuff @jthorton! One API break but it doesn't appear to affect any live code so that's OK. A little slippage in test coverage - see specific comments and please let me know if I've misunderstood something.

2024-07-12 09:22 UTC, jthorton commented on openff/qcsubmit/_tests/test_submissions.py
> +        assert record.specification.keywords.dihedral_ranges != dataset.dihedral_ranges
Yeah, this also confused me, but this comes down to the current tests not working as expected. I see the pattern of checking the length of a query to the test client to check the number of molecules is correct in the tests like [so](https://github.com/openforcefield/openff-qcsubmit/blob/aa6f377d6cd47688af6a942ce3be94012a6a7b37/openff/qcsubmit/_tests/test_submissions.py#L937) which works but this then empties the query as its a generator, so later in the test there is nothing to iterate over and compare. I believe the torsiondrive record we get from the dataset is [here](https://github.com/MolSSI/QCFractal/blob/970231b74bb8f6ef44e93d1fb37dee1924e562ee/qcportal/qcportal/torsiondrive/record_models.py#L131) and there is only one way to get to the keywords via `record.specification.keywords`.

2024-07-12 09:24 UTC, jthorton commented on openff/qcsubmit/_tests/test_submissions.py
> +def test_basic_submissions_wavefunction(fulltest_client, water):
Good point!

2024-07-15 09:15 UTC, jthorton commented on openff/qcsubmit/_tests/test_submissions.py
> -    await_results(client, check_fn=PortalClient.get_optimizations)
I think this whole test is a little confused and redundant as the dataset's internals have changed during the 0.50.0 update. The old test [here](https://github.com/openforcefield/openff-qcsubmit/blob/48943d8e7a5b6947001d29a9c629a65c4133dbd6/openff/qcsubmit/tests/test_submissions.py#L324) was making sure that specifications were correctly added to datasets on QCArchive which was handled by a specific function. This is now just part of the general [submit method](https://github.com/openforcefield/openff-qcsubmit/blob/aa6f377d6cd47688af6a942ce3be94012a6a7b37/openff/qcsubmit/datasets/datasets.py#L221-L225) and this [check_add_specs](https://github.com/openforcefield/openff-qcsubmit/blob/aa6f377d6cd47688af6a942ce3be94012a6a7b37/openff/qcsubmit/_tests/test_submissions.py#L98C5-L98C22) does the same thing. So I think we should be safe to remove this test.

2024-07-15 16:40 UTC, j-wags commented on openff/qcsubmit/_tests/test_submissions.py
> +        assert record.specification.keywords.dihedral_ranges != dataset.dihedral_ranges
Oh WOW, great catch. I hadn't considered that the loop was just skipping due to an empty iterator. Thanks for the attention to detail.

2024-07-15 16:41 UTC, j-wags commented on openff/qcsubmit/_tests/test_submissions.py
> -    await_results(client, check_fn=PortalClient.get_optimizations)
Awesome, thanks!

2024-07-19 00:17 UTC, j-wags approved these changes
Thanks @jthorton - Merging!

2024-07-19 21:38 UTC, merged